main: com.chellrose.minechell.App
name: MineChell
author: omg_shush
website: github.com/omg-shush/minechell
version: 0.4
api-version: '1.20'
commands:
  hat:
    description: Put any item on your head!
    usage: /hat
    permission: minechell.hat
  head:
    description: Apply a skin to a blank player head
    usage: /head
    permission: minechell.head
  tag:
    description: Play a game of tag!
    usage: /tag [list|online|join|leave|vote|unvote|set]
    permission: minechell.tag
permissions:
  minechell.hat:
    description: Allows a player to use /hat
    default: true
  minechell.head:
    description: Allows a player to use /head
    default: true
  minechell.tag:
    description: Allows a player to use /tag
    default: true
  minechell.tag.set:
    description: Manually override the current tagged player
    default: op
